# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KPI\scriptEditorDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scriptEditorDialog(object):
    def setupUi(self, scriptEditorDialog):
        scriptEditorDialog.setObjectName("scriptEditorDialog")
        scriptEditorDialog.resize(1062, 823)
        self.verticalLayout = QtWidgets.QVBoxLayout(scriptEditorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(scriptEditorDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(scriptEditorDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(scriptEditorDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.nameEdit = QtWidgets.QLineEdit(scriptEditorDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.folderEdit = QtWidgets.QLineEdit(scriptEditorDialog)
        self.folderEdit.setObjectName("folderEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.folderEdit)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddInput = QtWidgets.QToolButton(scriptEditorDialog)
        self.btnAddInput.setObjectName("btnAddInput")
        self.horizontalLayout.addWidget(self.btnAddInput)
        self.btnRemoveInput = QtWidgets.QToolButton(scriptEditorDialog)
        self.btnRemoveInput.setObjectName("btnRemoveInput")
        self.horizontalLayout.addWidget(self.btnRemoveInput)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.scriptTextEdit = QtWidgets.QPlainTextEdit(scriptEditorDialog)
        self.scriptTextEdit.setObjectName("scriptTextEdit")
        self.verticalLayout.addWidget(self.scriptTextEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(scriptEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(scriptEditorDialog)
        self.buttonBox.accepted.connect(scriptEditorDialog.accept)
        self.buttonBox.rejected.connect(scriptEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(scriptEditorDialog)

    def retranslateUi(self, scriptEditorDialog):
        _translate = QtCore.QCoreApplication.translate
        scriptEditorDialog.setWindowTitle(_translate("scriptEditorDialog", "Dialog"))
        self.label.setText(_translate("scriptEditorDialog", "Name"))
        self.label_2.setText(_translate("scriptEditorDialog", "Folder"))
        self.label_3.setText(_translate("scriptEditorDialog", "Inputs"))
        self.btnAddInput.setText(_translate("scriptEditorDialog", "..."))
        self.btnRemoveInput.setText(_translate("scriptEditorDialog", "..."))
