import os

ICONS_DIR = os.path.dirname(__file__)

LOCKED = os.path.join(ICONS_DIR, 'lock.png')
UNLOCKED = os.path.join(ICONS_DIR, 'unlock.png')
NEW = os.path.join(ICONS_DIR, 'add.png')
EDIT = os.path.join(ICONS_DIR, 'edit.png')
DELETE = os.path.join(ICONS_DIR, 'trash-can.png')
SAVE = os.path.join(ICONS_DIR, 'save.png')
CHECKED_CHECKBOX = os.path.join(ICONS_DIR, 'checked-checkbox.png')
UNCHECKED_CHECKBOX = os.path.join(ICONS_DIR, 'unchecked-checkbox.png')
UPLOAD = os.path.join(ICONS_DIR, 'upload.png')
CODE = os.path.join(ICONS_DIR, 'code.png')
COMMAND = os.path.join(ICONS_DIR, 'console.png')
FOLDER = os.path.join(ICONS_DIR, 'folder.png')
GPS_SIGNAL = os.path.join(ICONS_DIR, 'gps-signal.png')
GPS_DISCONNECTED = os.path.join(ICONS_DIR, 'gps-disconnected.png')
ROCKET = os.path.join(ICONS_DIR, 'rocket.png')
TOGGLE_ON = os.path.join(ICONS_DIR, 'toggle-on.png')
TOGGLE_OFF = os.path.join(ICONS_DIR, 'toggle-off.png')
TOGGLE_INDETERMINATE = os.path.join(ICONS_DIR, 'toggle-indeterminate.png')
CLEAR = os.path.join(ICONS_DIR, 'clear.png')
